# General
layout = {
    "expected_colors": [],
    "unexpected_colors": [],
    "threshold": 0,
    "ocr_blocks": {
        "match1_datetime": {
            "x": 1119,
            "y": 360,
            "w": 162,
            "h": 24,
            "colors": ["#ffffff"],
            "method": "pytesseract",
            "threshold": 100,
            "chars": " 0123456789:/",
        },
        "match2_datetime": {
            "x": 1119,
            "y": 589,
            "w": 162,
            "h": 24,
            "colors": ["#ffffff"],
            "method": "pytesseract",
            "threshold": 100,
            "chars": " 0123456789:/",
        },
        "match3_datetime": {
            "x": 1119,
            "y": 820,
            "w": 162,
            "h": 24,
            "colors": ["#ffffff"],
            "method": "pytesseract",
            "threshold": 125,
            "chars": " 0123456789:/",
        },
        "match4_datetime": {
            "x": 1119,
            "y": 855,
            "w": 162,
            "h": 24,
            "colors": ["#ffffff"],
            "method": "pytesseract",
            "threshold": 125,
            "chars": " 0123456789:/",
        },
    },
}
